format = """
[â–‘â–’â–“](#a3aed2)\
[ ïŒ“ ](bg:#a3aed2 fg:#1b1226 bold)\
$username\
[î‚´](bg:#6a7dbd fg:#a3aed2)\
$directory\
[î‚´](bg:#5b3e85 fg:#6a7dbd)\
$git_branch\
$git_status\
[î‚´](bg:#2c1e3f fg:#5b3e85)\
$nodejs\
$rust\
$golang\
$java\
$c\
$php\
[î‚´](bg:#1b1226 fg:#2c1e3f)\
\n$character"""

right_format = """$battery $time"""

[username]
style_user = "fg:#1b1226 bg:#a3aed2 bold"
style_root = "fg:#1b1226 bg:#f38ba8 bold"
format = '[ $user ]($style)'
disabled = false
show_always = true

[directory]
style = "fg:#f7c6e7 bg:#6a7dbd"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "fg:#f7c6e7 bg:#5b3e85"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#f7c6e7 bg:#5b3e85"
format = '[ $all_status$ahead_behind ]($style)'

[nodejs]
symbol = "îœ˜"
style = "fg:#a3aed2 bg:#2c1e3f"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "fg:#a3aed2 bg:#2c1e3f"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = "î˜§"
style = "fg:#a3aed2 bg:#2c1e3f"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰–"
style = "fg:#a3aed2 bg:#2c1e3f"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = "î˜"
style = "fg:#a3aed2 bg:#2c1e3f"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = "î˜ˆ"
style = "fg:#a3aed2 bg:#2c1e3f"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#f7c6e7 bg:#5b3e85"
format = '[ğŸ•“ $time]($style)'

[character]
success_symbol = "[ğŸœ](bold fg:#a3aed2)"
error_symbol = "[âœ—](bold fg:#f38ba8)"

[battery]
disabled = false
full_symbol = ""
charging_symbol = "âš¡"
discharging_symbol = "ğŸ”‹"
format = '[ $symbol$percentage ](fg:#f7c6e7 bg:#5b3e85)'
display = [{ style = "bold fg:#f7c6e7 bg:#5b3e85", threshold = 80 }]
